name: Build, Test and Publish Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      build-context:
        required: false
        type: string
        default: '.'
    secrets:
      dockerhub-username:
        required: true
      dockerhub-password:
        required: true

jobs:
  build-and-test:
    uses: ./.github/workflows/nodejs-reusable.yml
    with:
      run_lint: true
      run_test: true

  publish-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Docker Metadata
        id: meta
        run: |
          # 1. Pegamos apenas o nome do projeto (ex: boilerplate-simple-project-nodejs)
          # Removemos o usuário se ele vier no input e removemos tags
          RAW_NAME="${{ inputs.image-name }}"
          # Se tiver barra, pega só o nome após a barra, senão usa o nome inteiro
          if [[ "$RAW_NAME" == *"/"* ]]; then
            CLEAN_PROJECT_NAME=$(echo "${RAW_NAME##*/}" | cut -d':' -f1 | tr '[:upper:]' '[:lower:]')
          else
            CLEAN_PROJECT_NAME=$(echo "$RAW_NAME" | cut -d':' -f1 | tr '[:upper:]' '[:lower:]')
          fi

          # 2. Definimos o usuário fixo como 'hiagoscierry' que é o seu namespace real
          echo "image_path=docker.io/hiagoscierry/$CLEAN_PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-password }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build-context }}
          push: true
          tags: |
            ${{ steps.meta.outputs.image_path }}:latest
            ${{ steps.meta.outputs.image_path }}:${{ github.sha }}