name: Build, Test and Publish Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      build-context:
        required: false
        type: string
        default: '.'
    secrets:
      dockerhub-username:
        required: true
      dockerhub-password:
        required: true

jobs:
  build-and-test:
    uses: ./.github/workflows/nodejs-reusable.yml
    with:
      run_lint: true
      run_test: true

  publish-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Docker Metadata
        id: meta
        run: |
          # 1. Pegamos apenas o nome do projeto (ex: boilerplate-simple-project-nodejs)
          # Removemos qualquer namespace/usuário e tags
          RAW_NAME="${{ inputs.image-name }}"
          # Extrai nome do projeto (sem usuário, sem tag)
          CLEAN_PROJECT_NAME=$(echo "$RAW_NAME" | awk -F'/' '{print $NF}' | cut -d':' -f1 | tr '[:upper:]' '[:lower:]')
          # Extrai tag customizada, se houver
          CUSTOM_TAG=$(echo "$RAW_NAME" | grep -oE ':[^:]+$' | sed 's/^://')

          # Define o path base da imagem
          echo "image_path=docker.io/${{ secrets.dockerhub-username }}/$CLEAN_PROJECT_NAME" >> $GITHUB_OUTPUT
          # Exporta a tag customizada, se existir
          if [ -n "$CUSTOM_TAG" ]; then
            echo "custom_tag=$CUSTOM_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-password }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build-context }}
          push: true
          tags: |
            ${{ steps.meta.outputs.image_path }}:latest
            ${{ steps.meta.outputs.image_path }}:${{ github.sha }}
            ${{ steps.meta.outputs.image_path }}${{ steps.meta.outputs.custom_tag && format(':{0}', steps.meta.outputs.custom_tag) || '' }}